### ISSUE TITLE
Very promising work just sending kudos :)

### ISSUE THREAD

**Issue by njbuch** [landonr/lilygo-tdisplays3-esphome#12]
Hi there Landon and Adam

Just a heads-up from here, awaiting your work, so I can get started on deploying some TTGO S3 display devices on my setup.

It really looks promsing, but still over the top in terms of me getting it to work.

Thanks ;)

**Comment by guillempages** [comment]
@njbuch you might want to try using #14 as an external component; with it, you should be able to use this display as any other ESPHome display and follow other examples that you might find elsewhere to display meaningful data.

**Comment by njbuch** [comment]
I tried that, but never got it to work, did you progress on this?

**Comment by guillempages** [comment]
That PR was merged, so just using landonr's repository for the external components should work.
There is an "example.yaml" file there that you can use as a basis for your configuration, and iterate on that.

**Comment by njbuch** [comment]
Hmm, I tried again pulling the latest version. Ending in an infinite loop of re-starting, the device (usb-alert sound in windows keeps repeating while its attached.)

Here is what I do.
1. Pulling latest version of esphome
2. Pulling the latest version of  https://github.com/landonr/lilygo-tdisplays3-esphome
3. Copying the example.yaml and the tdisplays3 folder to my esphome dir.
4. Doing a "esphome run example.yaml , here is output:

`Linking .pioenvs\s3\firmware.elf
Retrieving maximum program size .pioenvs\s3\firmware.elf
Checking size .pioenvs\s3\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=         ]  12.3% (used 40312 bytes from 327680 bytes)
Flash: [====      ]  44.3% (used 813813 bytes from 1835008 bytes)
Building .pioenvs\s3\firmware.bin
esptool.py v4.2.1
Creating esp32s3 image...
Merged 2 ELF sections
Successfully created esp32s3 image.
esp32_create_combined_bin([".pioenvs\s3\firmware.bin"], [".pioenvs\s3\firmware.elf"])
esptool.py v4.5.1
Wrote 0xd6c80 bytes to file C:\Code\Home\ESPHomeInfra\.esphome\build\s3\.pioenvs\s3/firmware-factory.bin, ready to flash to offset 0x0` 

5. Going to https://web.esphome.io/ and installing for first use. Succeeding without hickups
6. Connecting again https://web.esphome.io/ and now "install" choosing the firmware from step 4. Waiting for erase and success.
7. Unounting and then disconnect from usb, and re-inserting.
8. Goes into endless loop

Where can I investigate further?

**Comment by landonr** [comment]
can you share your usb logs and your yaml

**Comment by njbuch** [comment]
The yaml is an exact copy of the example.yaml, only changed the secrets.yaml to match my network.
There is no output from the device, it just keeps rebooting.

**Comment by landonr** [comment]
you can see the usb logs at https://web.esphome.io/ if you connect and then hit logs, then press reboot. it seems like its boot looping but there may be something helpful there

**Comment by njbuch** [comment]
The only thing I am able to produce is:

``
Terminal disconnected: NetworkError: The device has been lost.
``

Please note to upload the firmware, I choose the USB/JTAG port.
![image](https://user-images.githubusercontent.com/6631425/229848691-0906f972-4c42-4837-8c66-1f381c6d174e.png)

To me, it seems that some more fundamental boot firmware is missing, is there a prep-step before the esphome "Prepare for first use" can run?

There are 3 bin files in the build folder:
![image](https://user-images.githubusercontent.com/6631425/229849472-76cdfc53-4742-4d7c-8fb5-90ce73cd3a3a.png)

Would it make sense to upload one of these other than the firmware.bin?

**Comment by guillempages** [comment]
I think i had the same issue at the beginning; i could not claim the device.
It started working after flashing the "firmware-factory.bin" file

**Comment by njbuch** [comment]
I have now uploaded the firmware-factory.bin file giving this output:
``
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x15 (USB_UART_CHIP_RESET),boot:0x0 (DOWNLOAD(USB/UART0))
Saved PC:0x40378c9d
waiting for download
``

Uploading the generated firmware.bin still ends in bootloop after that.

Also tried 1. upload firmware-factory.bin, 2. "Prepare for first use", 3. Upload firmware.bin. But no change.

**Comment by patfelst** [comment]
Hi @njbuch have you tried not doing steps 1 - 3, but let ESPHome pull directly from github when you install? i.e. do a clean files first.

> Here is what I do.
> 
> 1. Pulling latest version of esphome
> 2. Pulling the latest version of  https://github.com/landonr/lilygo-tdisplays3-esphome
> 3. Copying the example.yaml and the tdisplays3 folder to my esphome dir.

Also try plugging the ESP32 board directly into a USB port on the PC that is running Home Assistant.

**Comment by njbuch** [comment]
Good news, the @patfelst tips worked! I am not sure, but pulling the dev-branch from esphome might be the trick - instead of the going with the esphome-latest release version?

I will start experimenting with some larger display designs and some sensors. 

Thank you all the for the assistance! :)
