### ISSUE TITLE
CONF_LOAD_SMOOTH_FONTS requires CONF_LOAD_FONTS to be true (otherwise it has no meaning).

### ISSUE THREAD

**Issue by landonr** [landonr/lilygo-tdisplays3-esphome#27]
CONF_LOAD_SMOOTH_FONTS requires CONF_LOAD_FONTS to be true (otherwise it has no meaning).
It would be nice to add a custom validator to throw an error if smooth fonts are requested but "standard" fonts are not.

Another option would be to change the if below, so that if either of the options is set, the "standard" fonts defines are set. (and then change the type to "Exclusive"; so that either "LOAD_FONTS" or "LOAD_SMOOTH_FONTS" is set.

I'm unsure/undecided which of both options I find better, but it's @landonr's repository anyway :-D

_Originally posted by @guillempages in https://github.com/landonr/lilygo-tdisplays3-esphome/pull/23#discussion_r1240757738_

**Comment by guillempages** [comment]
Fabian tested this and fixed in the original PR; I think we can close this issue without action.
