### ISSUE TITLE
Touchscreen platform fails after upgrading to ESPHome 2023.12.0

### ISSUE THREAD

**Issue by ChrisMD123** [landonr/lilygo-tdisplays3-esphome#48]
Upon upgrading to ESPHome 2023.12.0, the touchscreen component shows the following error:

"Couldn't find any component that can be use for 'display::Display'. Are you missing a hub declaration?."

This appears under
`touchscreen`
`  - platform: tdisplays3`

**Comment by guillempages** [comment]
This is the issue I was mentioning in #47. PR #50 should fix this issue
