### ISSUE TITLE
Update to esphome 12.6/12.7 fails

### ISSUE THREAD

**Issue by Tobi9111** [landonr/lilygo-tdisplays3-esphome#57]
Hello,

since there is the esphome update to 12.6/12.7 out, i can't update on this version on my tdisplay s3. I get this error on my both Displays:

[logs_example_run.txt](https://github.com/landonr/lilygo-tdisplays3-esphome/files/13988577/logs_example_run.txt)

Someone know how i can fix it? Thanks a lot in advance!
Best regards

Tobi

**Comment by guillempages** [comment]
Duplicate of #56
