### ISSUE TITLE
External power solution

### ISSUE THREAD

**Issue by valeriotaccardo** [landonr/lilygo-tdisplays3-esphome#59]
GPIO15 need to be set to HIGH during boot to permit an external power on 5V pin. Without it, ESP don't turn on. 
I've done this:

esphome:
  # ...
  on_boot:
    priority: -100.0
    # ...
    then:
      - switch.turn_off: power_en
  
switch:
  - platform: gpio
    pin: GPIO15
    id: power_en
    restore_mode: ALWAYS_ON

**Comment by valeriotaccardo** [comment]
Excuse me! This is the correct code!
esphome:

...
on_boot:
priority: -100.0
# ...
then:
**- switch.turn_on: power_en**

switch:

platform: gpio
pin: GPIO15
id: power_en
restore_mode: ALWAYS_ON

**Comment by mploetner** [comment]
ah solved my error. thx

**Comment by valeriotaccardo** [comment]
So, can I use the fixed code?

**Comment by mploetner** [comment]
your code is already working. I made a stupid mistake

**Comment by valeriotaccardo** [comment]
Perfect... I will try it tomorrow



<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Privo
di virus.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno ven 15 mar 2024 alle ore 14:53 mploetner ***@***.***>
ha scritto:
