### ISSUE TITLE
Help with showing sensor data from homeassitant

### ISSUE THREAD

**Issue by dborup** [landonr/lilygo-tdisplays3-esphome#9]
Hi

Can anybody help me showing sensor data instead of text?

**Comment by landonr** [comment]
it should be something like 
```
std::string displayString = atof(id(sensor_id).state());
displayControllerComponent->drawString(displayString);
```

**Comment by dborup** [comment]
> it should be something like
> 
> ```
> std::string displayString = atof(id(sensor_id).state());
> displayControllerComponent->drawString(displayString);
> ```

I am not sure I get it.

I have this:
sensor:
  - platform: homeassistant
    id: inside_temperature
    entity_id: sensor.badevaerelse_sensor_temperature
    internal: true
interval:
  - interval: 1s
    then:
    - lambda: |-
        std::string displayString = atof(id(inside_temperature).state());
        displayControllerComponent->drawString(displayString);

and get this error 
x/config/esphome/s3.yaml: In lambda function:
/config/esphome/s3.yaml:47:66: error: expression cannot be used as a function
         std::string displayString = atof(id(inside_temperature).state());

**Comment by landonr** [comment]
sorry i tried coding without compiling and this is what happens
this worked for me
```
  std::string displayString = to_string(id(inside_temperature).state);
```
